font_family      hack
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 12.0
scrollback_lines 10000
url_prefixes http https file ftp
strip_trailing_spaces always
focus_follows_mouse yes
linux_display_server auto

# The amount the font size is changed by (in pts) when increasing/decreasing
# the font size in a running terminal.

font_size_delta 1

# Change the sizes of the lines used for the box drawing unicode characters
# These values are in pts. They will be scaled by the monitor DPI to arrive at
# a pixel value. There must be four values corresponding to thin, normal, thick,
# and very thick lines;
box_drawing_scale 0.001, 1, 1.5, 2


clipboard_control write-clipboard write-primary
