font_family      hack
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 12.0
scrollback_lines 10000
url_prefixes http https file ftp
strip_trailing_spaces always
focus_follows_mouse yes
linux_display_server auto


#You can change the font size for all top-level kitty OS windows at
# a time or only the current one.

map kitty_mod+equal     change_font_size all +1.0
map kitty_mod+minus     change_font_size all -1.0
map kitty_mod+backspace change_font_size all 0

# Change the sizes of the lines used for the box drawing unicode characters
# These values are in pts. They will be scaled by the monitor DPI to arrive at
# a pixel value. There must be four values corresponding to thin, normal, thick,
# and very thick lines;
box_drawing_scale 0.001, 1, 1.5, 2


clipboard_control write-clipboard write-primary
